import type { TableConfig } from "@/lib/crud/types";

export const contratosConfig: TableConfig = {
  name: "contratos",
  label: "Contratos",
  description: "Operaciones de venta y alquiler",
  primaryKey: "id_contrato",
  form: {
    title: "Gestionar Contratos",
    description: "Administra los Contratos disponibles.",
    columns: 3,
    submitLabel: "Guardar Contrato",
    cancelLabel: "Cancelar",
  },
  fields: [
    { name: "id_contrato", label: "ID", type: "number", readOnlyOnEdit: true },
    { name: "fecha_contrato", label: "Fecha Contrato", type: "date" },
    {
      name: "id_propiedad",
      label: "Propiedad (Nº de partida)",
      type: "select",
      required: true,
      foreignKey: {
        table: "propiedades",
        valueField: "id_propiedad",
        labelField: "n_partida",
      },
    },
    { name: "nro_contrato", label: "Nro Contrato", type: "text" },
    {
      name: "id_asociado",
      label: "Asociado",
      type: "select",
      foreignKey: {
        table: "asociados",
        valueField: "id_asociado",
        labelField: "nombre_completo",
      },
    },
    {
      name: "id_operacion",
      label: "Operación",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "operacion",
        valueField: "id",
        labelField: "operacion",
      },
    },
    {
      name: "id_tipo_contrato",
      label: "Tipo contrato",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "tipo_contrato",
        valueField: "id",
        labelField: "tipo_contrato",
      },
    },
    { name: "estado", label: "Estado activo", type: "boolean" },
    {
      name: "id_conformidad",
      label: "Conformidad",
      selectplus: false,
      type: "select",
      foreignKey: {
        table: "conformidad",
        valueField: "id",
        labelField: "tipo",
      },
    },
    {
      name: "id_estado",
      label: "Estado",
      selectplus: false,
      type: "select",
      foreignKey: {
        table: "estado",
        valueField: "id",
        labelField: "estado",
      },
    },
    {
      name: "id_mes_captacion",
      label: "Mes captación",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "mes",
        valueField: "id",
        labelField: "mes",
      },
    },
    {
      name: "id_tipo_moneda",
      label: "Tipo moneda Precio Inicio",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "tipo_moneda",
        valueField: "id",
        labelField: "tipo_moneda",
      },
    },
    { name: "precio_inicio", label: "Precio Inicio", type: "number" },
    { name: "fecha_fin", label: "Fecha fin", type: "date" },
    {
      name: "id_tipo_moneda_precio_venta",
      label: "Precio de Venta",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "tipo_moneda",
        valueField: "id",
        labelField: "tipo_moneda",
      },
    },
    { name: "precio_venta", label: "Precio Venta", type: "number" },
    { name: "fecha_inicio", label: "Fecha inicio", type: "date" },
    {
      name: "id_tipo_moneda_comision",
      label: "Tipo moneda Comision",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "tipo_moneda",
        valueField: "id",
        labelField: "tipo_moneda",
      },
    },
    { name: "comision", label: "Comisión", type: "number" },
    {
      name: "id_resource",
      label: "Documento",
      type: "select",
      foreignKey: {
        table: "resource",
        valueField: "id_resource",
        labelField: "url_resource",
      },
    },
    {
      name: "id_tipo_moneda_precio_maximo",
      label: "Tipo moneda Precio maximo",
      type: "select",
      selectplus: false,
      foreignKey: {
        table: "tipo_moneda",
        valueField: "id",
        labelField: "tipo_moneda",
      },
    },
    { name: "precio_maximo", label: "Precio maximo", type: "number" },
    {
      name: "id_mes_vencimiento",
      label: "Mes vencimiento",
      type: "select",
      selectplus: false,
      foreignKey: { table: "mes", valueField: "id", labelField: "mes" },
    },
    { name: "observaciones", label: "Observaciones", type: "textarea" },
  ],
};
